### ISSUE TITLE
Updated to 1.20.x

### ISSUE THREAD

**Issue by darkqueen1229** [sebastianbhahn/noNametaggedPeacefulDespawn#1]
Hello,

Would it at all be possible to get an update for this to 1.20.x? Specifically looking for 1.20.4 but will upgrade/downgrade if needed. Please?

**Comment by sebastianbhahn** [comment]
It was a relatively simple and useful mod. I honestly hoped someone else might pick it up or it might even end up included as a feature in the game by default. I'm not really a minecraft modder and haven't played the game in years. I'll see if I can though.

**Comment by sebastianbhahn** [comment]
> Would it at all be possible to get an update for this to 1.20.x? Specifically looking for 1.20.4 but will upgrade/downgrade if needed. Please?

So I don't have access to that account on curseforge and had to use another one to upload the updated mod.
It's still awaiting moderation approval, but after it's approved, I'll add a comment on the original mod page directing users to the new mod page under my new(er) curseforge account.

If you don't want to wait, you can get the jar for the mod here:
https://github.com/sebastianbhahn/noNametaggedPeacefulDespawn/tree/1.20.x/compiled%20jar
This should work for all 1.20 minecraft versions.
If you have any problems, submit a new ticket.

Also, I've made updated versions for 1.18-1.18.1, 1.18.2, and 1.19.x (x = all versions).
I'll be making one for 1.21 shortly.
Other versions can be found by checking project "branches" on the github page.
